"""add analytics columns

Revision ID: 03dc70935cc7
Revises: 6c9e87801614
Create Date: 2026-05-22 18:51:47.099444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03dc70935cc7'
down_revision: Union[str, Sequence[str], None] = '6c9e87801614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_snapshots', sa.Column('volume_1s', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('volume_10s', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('volume_60s', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('spread', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('imbalance', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('momentum', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('last_trade_ts', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('bid_size', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('ask_size', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('last_trade_size', sa.Float(), nullable=True))
    op.drop_column('market_snapshots', 'volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_snapshots', sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('market_snapshots', 'last_trade_size')
    op.drop_column('market_snapshots', 'ask_size')
    op.drop_column('market_snapshots', 'bid_size')
    op.drop_column('market_snapshots', 'last_trade_ts')
    op.drop_column('market_snapshots', 'momentum')
    op.drop_column('market_snapshots', 'imbalance')
    op.drop_column('market_snapshots', 'spread')
    op.drop_column('market_snapshots', 'volume_60s')
    op.drop_column('market_snapshots', 'volume_10s')
    op.drop_column('market_snapshots', 'volume_1s')
    # ### end Alembic commands ###
