"""backtest schema refactor

Revision ID: 1edf8debcf72
Revises: b30d333ee61f
Create Date: 2026-05-27 16:21:46.930825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1edf8debcf72'
down_revision: Union[str, Sequence[str], None] = 'b30d333ee61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_meta', sa.Column('series_ticker', sa.String(), nullable=True))
    op.create_index(op.f('ix_market_meta_series_ticker'), 'market_meta', ['series_ticker'], unique=False)
    op.add_column('market_snapshots', sa.Column('snapshot_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_market_snapshots_snapshot_time'), 'market_snapshots', ['snapshot_time'], unique=False)
    op.drop_column('market_snapshots', 'spread')
    op.drop_column('market_snapshots', 'volume_60s')
    op.drop_column('market_snapshots', 'momentum')
    op.drop_column('market_snapshots', 'volume_1s')
    op.drop_column('market_snapshots', 'imbalance')
    op.drop_column('market_snapshots', 'volume_10s')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_snapshots', sa.Column('volume_10s', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('imbalance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('volume_1s', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('momentum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('volume_60s', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('spread', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_market_snapshots_snapshot_time'), table_name='market_snapshots')
    op.drop_column('market_snapshots', 'snapshot_time')
    op.drop_index(op.f('ix_market_meta_series_ticker'), table_name='market_meta')
    op.drop_column('market_meta', 'series_ticker')
    # ### end Alembic commands ###
