"""modifications to markets table

Revision ID: 6c9e87801614
Revises: f611dc52ec1c
Create Date: 2026-02-12 21:05:12.858677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c9e87801614'
down_revision: Union[str, Sequence[str], None] = 'f611dc52ec1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_snapshots', sa.Column('title', sa.String(), nullable=True))
    op.add_column('market_snapshots', sa.Column('open_time', sa.DateTime(), nullable=True))
    op.add_column('market_snapshots', sa.Column('close_time', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_market_snapshots_market_id'), table_name='market_snapshots')
    op.drop_column('market_snapshots', 'market_id')
    op.drop_column('market_snapshots', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_snapshots', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('market_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_market_snapshots_market_id'), 'market_snapshots', ['market_id'], unique=False)
    op.drop_column('market_snapshots', 'close_time')
    op.drop_column('market_snapshots', 'open_time')
    op.drop_column('market_snapshots', 'title')
    # ### end Alembic commands ###
