"""restore analytics columns to snapshots

Revision ID: 73b6190bbdd5
Revises: c4dd9f44105e
Create Date: 2026-06-11 01:49:39.309214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b6190bbdd5'
down_revision: Union[str, Sequence[str], None] = 'c4dd9f44105e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_snapshots', sa.Column('spread', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('imbalance', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('momentum', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('volume_1s', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('volume_10s', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('volume_60s', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_snapshots', 'volume_60s')
    op.drop_column('market_snapshots', 'volume_10s')
    op.drop_column('market_snapshots', 'volume_1s')
    op.drop_column('market_snapshots', 'momentum')
    op.drop_column('market_snapshots', 'imbalance')
    op.drop_column('market_snapshots', 'spread')
    # ### end Alembic commands ###
