"""market_meta refactor

Revision ID: b30d333ee61f
Revises: 03dc70935cc7
Create Date: 2026-05-23 19:55:35.202743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b30d333ee61f'
down_revision: Union[str, Sequence[str], None] = '03dc70935cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('event_ticker', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=True),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_meta_event_ticker'), 'market_meta', ['event_ticker'], unique=False)
    op.create_index(op.f('ix_market_meta_id'), 'market_meta', ['id'], unique=False)
    op.create_index(op.f('ix_market_meta_ticker'), 'market_meta', ['ticker'], unique=True)
    op.drop_index(op.f('ix_market_snapshots_event_ticker'), table_name='market_snapshots')
    op.drop_column('market_snapshots', 'prev_yes')
    op.drop_column('market_snapshots', 'result')
    op.drop_column('market_snapshots', 'open_time')
    op.drop_column('market_snapshots', 'close_time')
    op.drop_column('market_snapshots', 'event_ticker')
    op.drop_column('market_snapshots', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_snapshots', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('event_ticker', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('close_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('open_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('result', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('prev_yes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_market_snapshots_event_ticker'), 'market_snapshots', ['event_ticker'], unique=False)
    op.drop_index(op.f('ix_market_meta_ticker'), table_name='market_meta')
    op.drop_index(op.f('ix_market_meta_id'), table_name='market_meta')
    op.drop_index(op.f('ix_market_meta_event_ticker'), table_name='market_meta')
    op.drop_table('market_meta')
    # ### end Alembic commands ###
