"""add compound index on snapshots ticker time

Revision ID: c4dd9f44105e
Revises: 1edf8debcf72
Create Date: 2026-06-02 00:29:37.946744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4dd9f44105e'
down_revision: Union[str, Sequence[str], None] = '1edf8debcf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_snapshots_ticker_time', 'market_snapshots', ['ticker', 'snapshot_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_ticker_time', table_name='market_snapshots')
    # ### end Alembic commands ###
