"""initial commit

Revision ID: f611dc52ec1c
Revises: 
Create Date: 2026-02-09 14:55:33.756244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f611dc52ec1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('event_ticker', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('yes_bid', sa.Float(), nullable=True),
    sa.Column('no_bid', sa.Float(), nullable=True),
    sa.Column('yes_ask', sa.Float(), nullable=True),
    sa.Column('no_ask', sa.Float(), nullable=True),
    sa.Column('prev_yes', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_event_ticker'), 'market_snapshots', ['event_ticker'], unique=False)
    op.create_index(op.f('ix_market_snapshots_id'), 'market_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_market_id'), 'market_snapshots', ['market_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_ticker'), 'market_snapshots', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_snapshots_ticker'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_market_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_event_ticker'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
